#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Show training progress (train/test mistakes, learning rate) for each epoch.
Operates on a SCN result table (generated by parse_wp2.log).

@author: moi
"""

import matplotlib.pyplot as plt
import numpy as np

fig, ax1 = plt.subplots()
ax1.set_xlim(0)
ax1.set_ylim(0, 100)
ax1.set_xlabel("Epoch")
ax1.set_ylabel("% Mistakes")
ax2 = ax1.twinx()
ax2.set_ylim(0, .01)
ax2.set_ylabel("Learning Rate")

for experiment in ["SCN_flowcam_group1_0_2017-08-14-10-20", "SCN_flowcam_group1_0_2017-08-31-10-17"]:
    tab_fn = "/datapc/ob/mschroeder/Ecotaxa/Results/{}/wp2.csv".format(experiment)
        
    data = np.genfromtxt(tab_fn, delimiter=",", names=True)
    
    test_mistakes = sum(data["test_{:d}_mistakes".format(i)] for i in range(1,4)) / 3
    
    ax1.plot(data["epoch"], data["train_mistakes"], label="Train mistakes ({})".format(experiment))
    ax1.plot(data["epoch"], test_mistakes, label="Test mistakes ({})".format(experiment))
    
    ax2.plot(data["epoch"], data["current_lr"], label="LR ({})".format(experiment))
    
    print(np.min(test_mistakes), 100 - np.min(test_mistakes))
    
ax1.legend(loc="upper left")
ax2.legend(loc="upper right")